django_celery_tutorial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('tutorial.urls', 'tutorial'), namespace='tutorial')),
]

tutorial/urls.py
from django.contrib import admin
from django.urls import path
from tutorial import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('task_use_celery/', views.task_use_celery, name='task_use_celery'),
    path('task_not_use_celery/', views.task_not_use_celery, name='task_not_use_celery'),

]

tutorial/models.py
from django.db import models

# Create your models here.

tutorial/views.py
from django.core.mail import send_mail
from django.shortcuts import render

from tutorial.tasks import task_mail


# Create your views here.


def dashboard(request):
    return render(request, "tutorial/dashboard.html")


def task_use_celery(request):
    task_mail.delay()
    return render(request, "tutorial/process_done.html")


def task_not_use_celery(request):
    subject = "not celery subject test"
    message = "not celery message test"
    recipient = ["xxxxxx@gmail.com", "xxxxxx@gmail.com", "xxxxxx@yahoo.com.tw"]
    send_mail(
        subject,
        message,
        "admin@celery_test.com",
        recipient,
    )
    return render(request, "tutorial/process_done.html")

tutorial/templates/tutorial/base.html
{% load static %}
{% load bootstrap3 %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>
<body>

<div class="container">
    <div class="jumbotron">
        <h1>Django Celery Tutorial</h1>
        <p>celery tutorial</p>
    </div>

    {% block content %}
    {% endblock %}

</div>
</body>
</html>

tutorial/templates/tutorial/dashboard.html
{% extends "tutorial/base.html" %}
{% load static %}
{% load bootstrap3 %}

{% block title %}
    dasshboard
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-md-3">
{#            <form action="{% url "tutorial:task_use_celery" %}" method="post">#}
{#                {% csrf_token %}#}
{#                <button type="submit" class="btn btn-primary">use celery</button>#}
{#            </form>#}
            <a href="{% url "tutorial:task_use_celery" %}" class="btn btn-primary" role="button">use celery</a>
        </div>
        <div class="col-md-3">
{#            <form action="{% url "tutorial:task_not_use_celery" %}" method="post">#}
{#                {% csrf_token %}#}
{#                <button type="submit" class="btn btn-warning">not use celery</button>#}
{#            </form>#}
            <a href="{% url "tutorial:task_not_use_celery" %}" class="btn btn-warning" role="button">not use celery</a>
        </div>
    </div>

{% endblock %}

tutorial/templates/tutorial/process_done.html
{% extends "tutorial/base.html" %}
{% load static %}
{% load bootstrap3 %}

{% block title %}
    Thank You
{% endblock %}

{% block content %}

<div class="well well-lg">Thank You ! Please go to the mailbox to receive ！ </div>

{% endblock %}